### ISSUE TITLE
Question: How to show the SVG files in Android-Studio, using "Android" mode?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [trello/victor#10]
It's just that resources are visible there, but not the SVG files:

![untitled20150322213119](https://cloud.githubusercontent.com/assets/5357526/6771016/d5ff91b6-d0da-11e4-8077-8171c66ce269.png)

Do I have to switch the mode? Or is there anyway else?
Is it possible to put the svg files into res/raw or assets , and while building, to ignore them ?

**Comment by dlew** [comment]
There isn't a way to do it right now; the Android project view is highly curated.

I don't believe there is a way to include it in `/res/raw` and not have it be included in the build. You could exclude those files from the source set, but then the Android project view wouldn't see it. :)

**Comment by AndroidDeveloperLB** [comment]
That's too bad. was hoping that a nicer integration would be possible.
But it's an open IDE, no? isn't there a way to make a plugin that would make it work this way?
or use gradle to do it?

**Comment by dlew** [comment]
I could look into it, I'm not sure how high priority it is since you can view all those resources in project mode.

**Comment by AndroidDeveloperLB** [comment]
I know. But project mode also shows a lot of junk and doesn't merge resources. :(

**Comment by dlew** [comment]
This isn't really something that can be fixed by this plugin; it's up to the IDE devs to make it compatible.
