### ISSUE TITLE
add option to generate images in mipmap instead of drawable folder

### ISSUE THREAD

**Issue by GabrielCastro** [trello/victor#11]

**Comment by dlew** [comment]
For what purpose? Launcher icons?

I've been considering having the sourceSet define a tree so you can use qualifiers, e.g.

```
/svg/drawable/
/svg/drawable-land/
/svg/mipmap/
```

I think that would probably solve your problem.

**Comment by GabrielCastro** [comment]
yeah launcher icon is what I really want it for

**Comment by dlew** [comment]
Victor is in maintenance mode, so not adding this feature anytime soon.
