### ISSUE TITLE
After editing SVG from Google Icon Pack not working

### ISSUE THREAD

**Issue by pimato** [trello/victor#12]
Hey dear Trello and thanks already for this awesome Library,

after I opened and edited a svg icon from Google it is showing me like that : 

![pic](https://cloud.githubusercontent.com/assets/5337809/6903294/85fe022a-d719-11e4-8349-105718c8f2f5.png)

why that ? 

Can someone tell me how to save my svg's in Illustrator so I can use this library ? 

thanks for all your work,
cheers pimato

**Comment by dlew** [comment]
If you edited the SVG, then I would bet that whatever changes you did messed up the SVG.

**Comment by pimato** [comment]
thanks for the quick reply,

I changed nothing, just saved it again ... 
maybe someone has also the problem ?

**Comment by pimato** [comment]
Alright dew,

I got it ! 

Illustrator is changing it by default. You need to take off the tick at Responsive or in german on the screenshot (interaktiv) .

![screenshot 2015-03-30 20 23 53](https://cloud.githubusercontent.com/assets/5337809/6903518/14967368-d71b-11e4-92e8-3189f9acea60.png)

**Comment by abdyer** [comment]
I ran into this problem as well. If anyone else ends up with 1x1, 2x2 or similarly small generated PNGs, this is probably the fix. Thanks!
