### ISSUE TITLE
When are generated resources going to be fully supported?

### ISSUE THREAD

**Issue by AndreasBackx** [trello/victor#15]
The "Known issues" section states the following:
> Android Studio doesn't recognize generated resources in XML, so autocomplete doesn't work and you get warnings (even though the code works fine). **Generated resources should be fully supported in future versions of the Android gradle plugin.**

Could there be specified when or given any extra information? It's quite a bummer that you cannot use the SVG-files in the preview, making Victor kind of a solution to a problem only once you have designed your layouts.

**Comment by dlew** [comment]
That's not really up to me. It's up to Android Studio to start supporting it.

There's a bug on the Android tracker about it right now: https://code.google.com/p/android/issues/detail?id=160646

**Comment by AndreasBackx** [comment]
I knew it wasn't up to you, thank you for giving the me issue on the Android tracker.
