### ISSUE TITLE
Gradle daemon breaks incremental task

### ISSUE THREAD

**Issue by gabrielittner** [trello/victor#16]
When the daemon is activated rasterizeSvgsForDebug is always run. From the debug log:
Value of input property 'includeDensities' has changed for task ':BizCal2-Android:rasterizeSvgsForDebug'

**Comment by dlew** [comment]
I took a brief look and this has me stumped; I'm not sure why the daemon should make a difference. Created a topic here, looking for further help: https://discuss.gradle.org/t/custom-task-never-up-to-date-when-running-daemon/9525

**Comment by dlew** [comment]
It turned out to be an issue with Gradle itself. I've implemented a workaround in the meantime so that the task is considered up-to-date properly.

**Comment by gabrielittner** [comment]
:+1:
