### ISSUE TITLE
preview in layout files

### ISSUE THREAD

**Issue by TheWhiteLlama** [trello/victor#18]
Hi there!

Is there a way to display the rasterized svg results in the layout previews already?
For me it works fine to display the drawables in the app itself, but Android Studio is not able to find the drawables while editing the layouts. making it hard to see whether I've designed the layouts correctly. Sometimes I also want to use wrap_content for the ImageViews but this does not work either (it actually works in the app but I also want to see how the layout would look like if the sizes were defined by wrap_content), since there are no drawables found.

Did I setup the library correctly or did I forget something?

**Comment by dlew** [comment]
Unfortunately this is a limitation with Android Studio at the moment. Hopefully they'll fix generated resources integration in a future release.

**Comment by TheWhiteLlama** [comment]
oh I see. That's a pity. I hope they are already thinking about supporting this features in the near future! Thank you for the clarification!
