### ISSUE TITLE
Improvement for getting started

### ISSUE THREAD

**Issue by ciskeboekelo** [trello/victor#19]
Hi, 

I'm just trying this out now, and it took me a while to get it working because the contents of the SVG file I was using I got from http://materialdesignicons.com/ and it's different from what is required by Victor.

The materialdesignicons svg xml looks like:

    <svg style="width:24px;height:24px" viewBox="0 0 24 24">
        <path fill="#000000" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" />
    </svg>

while Victor thinks it should look like this:

    <svg xmlns="http://www.w3.org/2000/svg" width="28pt" height="28pt" viewBox="0 0 24 24">
        <path fill="#000000" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" />
    </svg>

And so it 
- misses the namespace, which causes Victor to not generate the resources at all
- has defined the dimensions diffently which seems to result in zero width drawables

Perhaps something can be done to avoid other people making the same mistake and getting stuck on it by
- Adding a tip to the readme?
- Generating an error message during building when the svg syntax is not as required?
- Supporting the syntax as used at materialdesignicons.com ?

**Comment by zoltanf** [comment]
Thank you for this. I just run into the exact same issue, and you post helped resolve what was wrong.

**Comment by ciskeboekelo** [comment]
@zoltanf Glad it helped!

**Comment by dlew** [comment]
Victor uses the Batik rasterizer, which doesn't support namespace-less SVGs:

```
Converting file.svg to file.png ... org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Root element namespace does not match that requested:
Requested: http://www.w3.org/2000/svg
Found: null
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.apps.rasterizer.SVGConverter.transcode(Unknown Source)
	at org.apache.batik.apps.rasterizer.SVGConverter.execute(Unknown Source)
	at org.apache.batik.apps.rasterizer.Main.execute(Unknown Source)
	at org.apache.batik.apps.rasterizer.Main.main(Unknown Source)
... error (SVGConverter.error.while.rasterizing.file)
```

The width/height being defined by the style is a red herring. If you add `xmlns` to the file it should rasterize just fine.

IMO the easiest solution would be to get http://materialdesignicons.com/ to change their SVG generator so that it includes xmlns. I'm not sure why they don't right now, according to a quick search the only time that's valid SVG [is if you're embedding it inline in an HTML file](http://stackoverflow.com/a/18468348/60261).

**Comment by dlew** [comment]
In fact, now that I look at it, the SVGs *do* include xmlns if you download them, just not if you view them. I've filed an issue with the MaterialDesign project: https://github.com/Templarian/MaterialDesign/issues/439

**Comment by ciskeboekelo** [comment]
Thanks for the quick reply!

A few things:

1. Wouldn't it be preferable to have the build fail when Batik throws an exception? It would make it much more obvious what is going wrong. Now it fails on "No resource found that matches the given name ..."

2. Yes having the MaterialDesign project add the namespace makes sense, thanks for creating an issue.

3. Using the victor sample project, and changing just the way the dimensions are specified in ic_laptop.svg from 

```width="24pt" height="24pt"```

to

    style="width:24px;height:24px"

results in a 3 by 3 png in the generated xxhdpi folder, containing only a shadowy gradient.

**Comment by dlew** [comment]
Those should be split out into separate issues I think. I suspect the Batik rasterizer version just needs to get upgraded to handle the third problem. Regarding the first, we could kill the build, not too hard.

Frankly, though, Victor's lifespan is not going to be much longer. Google is developing a tool which basically does exactly the same thing. Once it's released this project will most likely be deprecated.

**Comment by ciskeboekelo** [comment]
Ah, that's good news! 
Though not for Victor. Poor Victor...

Any idea when that tool is expected to be finished?

I'll leave this issue for having the build fail, and will create another for upgrading the Batik rasterizer.

**Comment by dlew** [comment]
For the record, [Templarian](https://github.com/Templarian) said that the "view SVG" is not supposed to be used for anything but web dev. So at its core the material design page is being misused anyways to create this issue.

**Comment by ciskeboekelo** [comment]
Yes, exactly.
Though I'd argue that I'd only have lost a minute or two of my time if victor had stopped the build from failing before it failed because of the missing resources. As it was, It took me while to figure out was going on.
Anyway, thanks for your time today!
