### ISSUE TITLE
can't able to build the project in Android Studio 1.3 Mac OS Yosemite

### ISSUE THREAD

**Issue by farhanmunir50** [trello/victor#22]
when i change the the JVMVersion of android studio to this 

<key>JVMVersion</key>
<string>1.7*</string>
my android studio did not work and display jre errors ,

Android Studio was unable to find a valid JVM. 

 by defaults its JVMVersion is 
<string>1.6*,1.7+</string>

when i build first time its displays tool kit error 

Error:Execution failed for task ':app:rasterizeSvgsForDebug'.
> Toolkit not found: apple.awt.CToolkit

second time studio shows Batik error

Error:Execution failed for task ':app:rasterizeSvgsForDebug'.
> Could not initialize class org.apache.batik.bridge.CursorManager

**Comment by dlew** [comment]
Do you have JVM 1.7 installed on your computer?

**Comment by farhanmunir50** [comment]
i have java 1.8 
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

**Comment by dlew** [comment]
This seems more like a problem with Android Studio not accepting JVM 1.7 than a Victor problem.

It's a known limitation that you can't run Victor on JVM 1.6 because it lacks `CToolkit`, which is why it's advised to upgrade to 1.7.

**Comment by farhanmunir50** [comment]
@dlew  do you think 1.8 lack of CToolkit ?

**Comment by dlew** [comment]
1.8 ought to have it too, I'd think. What's most important is just that you're running Oracle's JVM, not the one included with the mac, which doesn't have it.

**Comment by farhanmunir50** [comment]
@dlew can u please provide download link so i can install correct version

**Comment by dlew** [comment]
Didn't you just say that you have 1.8 installed?

**Comment by farhanmunir50** [comment]
yes i have

**Comment by dlew** [comment]
I'm trying to help out, but I'm getting confused here:

1. You've never told me what error you're getting from Android Studio, which seems to be the root of the problem.
2. You claim you've got the proper JVMs installed, but then also ask for which JVMs to install.

**Comment by farhanmunir50** [comment]
@dlew  sorry for inconvenience , i just say yes i have installed jvm 1.8 and i mentioned the errors in the questions and i ask for jvm 1.7 download link because i upgrade jvm 1.6 to 1.8

**Comment by dlew** [comment]
You did not tell me the errors. All you said was

> my android studio did not work and display jre errors ,

The errors below that are the ones that happen if you are running on the default JVM 1.6.

**Comment by farhanmunir50** [comment]
when android studio running on jvm 1.8 it displays these errors
when i build first time its displays tool kit error

Error:Execution failed for task ':app:rasterizeSvgsForDebug'.

Toolkit not found: apple.awt.CToolkit
second time studio shows Batik error

Error:Execution failed for task ':app:rasterizeSvgsForDebug'.

Could not initialize class org.apache.batik.bridge.CursorManager

**Comment by dlew** [comment]
Okay, I misunderstood, I thought you were still talking about 1.6 with those errors.

What happens if you run builds from the command line?

**Comment by farhanmunir50** [comment]
i dont know how to build from command line

**Comment by dlew** [comment]
````
$ cd path/to/app
$ ./gradlew assemble
```

**Comment by farhanmunir50** [comment]
apply plugin: 'com.android.application'
apply plugin: 'com.trello.victor'

// Make sure to apply this plugin *after* the Android plugin

android {
    compileSdkVersion 22
    buildToolsVersion "23.0.0 rc2"

    defaultConfig {
        applicationId "croem.com.cellpago"
        minSdkVersion 11
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            svg.srcDir 'src/main/svg'
        }
    }

}


victor {
    // Any assets defined in relative terms needs a base DPI specified
    svgDpi = 72

    // Do not generate these densities for SVG assets
    excludeDensities = [ 'ldpi', 'xxxhdpi' ]
}


dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:design:22.2.0'
    compile 'com.google.code.gson:gson:2.3.1'
}

**Comment by farhanmunir50** [comment]
@dlew here is the my gradle file

**Comment by dlew** [comment]
I'm beginning to think that this is a better question for [StackOverflow](http://stackoverflow.com/), where you'll get an answer sooner. (This tracker is for bug reports with test cases & feature requests only.)

If you get a reproducible test case where this fails, then we can reopen and investigate further.

**Comment by farhanmunir50** [comment]
@dlew just confirm one thing we just need to update build.gradle to use this plugin or something else so i can do
