### ISSUE TITLE
Unsupported type "path"

### ISSUE THREAD

**Issue by sashabelonogov** [trello/victor#23]
Most of the .svg files that I use are made with the "path" and I get this error:

Error:Execution failed for task ':Allryder:mergeDebugResources'.
> Unsupported type 'path' in file /Users/VL/Documents/android/src/main/res/svg/=-=.svg

Will it be hard to support the path?

**Comment by sashabelonogov** [comment]
Example of an image:

<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
<path fill="#3282C4" d="M15,0.2C7.8,0.2,2,6,2,13.2c0,8.1,11.4,16,11.9,16.3c0.3,0.2,0.7,0.3,1,0.3s0.7-0.1,1-0.3
	c0.5-0.3,11.9-8.2,11.9-16.3C27.9,6,22.1,0.2,15,0.2z M15,16.8c-2,0-3.7-1.7-3.7-3.7s1.7-3.7,3.7-3.7s3.7,1.7,3.7,3.7
	S17,16.8,15,16.8z"/>
</svg>

**Comment by dlew** [comment]
I'm not entirely clear on what you're doing. What is "madden"?

What do your sourcesets look like?

**Comment by sashabelonogov** [comment]
Here is an example of the .svg:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 28 32" enable-background="new 0 0 28 32" xml:space="preserve">
<path fill="#EF3E4D" d="M14,0C6.3,0,0,6.3,0,14c0,8.8,12.3,17.3,12.9,17.7c0.3,0.2,0.7,0.3,1.1,0.3s0.8-0.1,1.1-0.3
	C15.7,31.3,28,22.8,28,14C28,6.3,21.7,0,14,0z M22.2,18.9L14,23.7l-8.2-4.7V9.4l4.1,2.4v4.7l4.1,2.4l4.1-2.4v-4.7L14,9.4V4.7
	l8.2,4.7V18.9z"/>
</svg>
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 28 32" enable-background="new 0 0 28 32" xml:space="preserve">
<path fill="#EF3E4D" d="M14,0C6.3,0,0,6.3,0,14c0,8.8,12.3,17.3,12.9,17.7c0.3,0.2,0.7,0.3,1.1,0.3s0.8-0.1,1.1-0.3
	C15.7,31.3,28,22.8,28,14C28,6.3,21.7,0,14,0z M22.2,18.9L14,23.7l-8.2-4.7V9.4l4.1,2.4v4.7l4.1,2.4l4.1-2.4v-4.7L14,9.4V4.7
	l8.2,4.7V18.9z"/>
</svg>

```

**Comment by dlew** [comment]
Besides that you copy/pasted the same SVG twice, it looks valid.

Is there a reproducible example you can provide?
