### ISSUE TITLE
Option to Put Generated PNGs into Non-Build Drawable Folders

### ISSUE THREAD

**Issue by eugenkiss** [trello/victor#29]
Would you support an option to put the generated PNGs into the non-build drawable folders (e.g. `src/main/drawable-hdpi`)? This would help or at least be a workaround for the problems #15 and #18. I'm thinking of something like

    victor {
        useNonBuildOutput = true
    }

I might look into it myself but I would appreciate your opinion on this proposal and if you're in favor of it I'd also have nothing against some pointers about a potential implementation.

**Comment by dlew** [comment]
Preferably, I'd like there to be the fewest number of knobs possible. The more configuration, the more confusion (in general).

The main advantage that Victor confers is being able to compile SVGs at build time; if you're wanting to precompile SVGs to another directory then you could do it fairly simply with the Batik tool and a little shell scripting. (Indeed, this was how some other solutions did it before Victor.)

**Comment by eugenkiss** [comment]
> Preferably, I'd like there to be the fewest number of knobs possible. The more configuration, the more confusion (in general).

I fully understand.

> The main advantage that Victor confers is being able to compile SVGs at build time; if you're wanting to precompile SVGs to another directory then you could do it fairly simply with the Batik tool and a little shell scripting. (Indeed, this was how some other solutions did it before Victor.)

I still want to compile the generated PNGs (and overwrite existing ones) at build time :) but I want to have the generated PNGs where I would normally put PNGs manually and not in the build folder simply to workaround #15 and #18.

I could write a shell script that uses Batik to generate the PNGs. Then I could write a Gradle integration for this script that regenerates the PNGs at build time whenever there was a change* in the SVG folder in the mean time (instead of simply on every build or with a manual command). But then I've basically recreated Victor, haven't I?

* I don't know how the change detection works right now but I have the feeling it relies on the output being in the `build` folder.

In any case, I might just create a personal fork with the feature or write a shell script and will manually generate PNGs.

Thanks for your input :+1: .

**Comment by dlew** [comment]
>  I want to have the generated PNGs where I would normally put PNGs manually and not in the build folder simply to workaround #15 and #18.

Ah, I see your intention here.

First, that it's in `/build/` makes no difference. In fact, it doesn't matter where you put it. It hooks into the build system by using `registerResGeneratingTask()`, which lets you specify the location. It's that method which doesn't properly handle resources.

(It's not the case that the resources are automatically absorbed just because they're in `/build/` - that's what I tried initially, but it doesn't work very well!)

The alternative approach would be to place PNGs directly into the source folders, pre-build-steps. There's a couple problems with this approach (and why I never went down this road):

- It's impossible to clean your builds anymore, since there's no way to know if that file in `/drawable-xhdpi/` was placed there by Victor vs. manually.
- You can accidentally check in Victor assets to source control (a problem compounded by the lack of clean).

**Comment by eugenkiss** [comment]
Thanks a lot for your detailed answer. Especially the last two points now make the advanted of the `/build/` folder approach clear to me. And I understand now that hooking into a particular build lifecycle method (`registerResGeneratingTask`) is what brings the problems and not the fact that the generated PNGs lie in `/build/`.

> The alternative approach would be to place PNGs directly into the source folders, pre-build-steps. There's a couple problems with this approach (and why I never went down this road):
> * It's impossible to clean your builds anymore, since there's no way to know if that file in /drawable-xhdpi/ was placed there by Victor vs. manually.
> * You can accidentally check in Victor assets to source control (a problem compounded by the lack of clean).

Just a rough idea I had to (hopefully) circumvent these two problems. Why not specify an extra resources folder `res-victor` (see [here|http://stackoverflow.com/a/28200250/283607]) and make Victor put the generated PNGS into `res-victor/drawable-hdpi` etc. Add `res-victor` to `.gitignore` and when cleaning simply delete `res-victor`. It sounds good in my mind right now bu maybe I'm just too sleepy already. What do you think about this approach? Do you see any obstacles?

**Comment by dlew** [comment]
Actually, you could do one better than `.gitignore` by just specifying another resource folder in android source set.

Imagine, though, that the bug in the IDE was fixed. Would these options be helpful at all then? I don't think they would.

I'd rather this library be in the ideal state than a hacky one, and right now Victor works (it just shows errors in the IDE).

**Comment by eugenkiss** [comment]
> Actually, you could do one better than .gitignore by just specifying another resource folder in android source set.

That's what I meant ;).

> Imagine, though, that the bug in the IDE was fixed. Would these options be helpful at all then? I don't think they would.
> I'd rather this library be in the ideal state than a hacky one, and right now Victor works (it just shows errors in the IDE).

Fair enough! Let's close this issue then.
