### ISSUE TITLE
Option to Use hdpi/xhdpi/... Instead of mdpi as Baseline Resolution

### ISSUE THREAD

**Issue by eugenkiss** [trello/victor#30]
As far as I understand if an SVG file has values for its height and width they are interpreted as the height and width of the correspondingly generated mdpi PNG. The following 48x48 SVG will become a 72x72 generated hdpi PNG: https://gist.github.com/eugenkiss/7ae6744e8aec88119ae0

What do you think about being able to define a baseline (l/m/h/xh/xxh/xxxh) dpi such that the above 48x48 SVG will result in a 48x48 generated hdpi PNG (and a 32x32 mdpi PNG etc.)?

**Comment by dlew** [comment]
Would the `svgDpi` option work here? As long as you define your SVGs with relative sizing then you can get any effect you want.

**Comment by eugenkiss** [comment]
I thought so but I might be just too stupid to figure it out. I assume an SVG with relative sizing is one where the root element does neither have a `width` nor a `height` attribute? Has the following SVG relative sizing?: https://gist.github.com/eugenkiss/44bfe03aad448ec60348

In any case, I tried to use different `svgDpi` values for the above SVG that has no width/height attributes and I run into the same issue as described in #12.

**Comment by dlew** [comment]
It's one where you use `pt`, `em`, etc. instead of `px` for the SVG.

**Comment by eugenkiss** [comment]
Thanks :). That works :+1:

**Comment by eugenkiss** [comment]
Our designer tried to export assets as SVGs with relative sizing from Photoshop. But not matter what option he tried the resulting SVG files never had any unit suffixes for their width/height. When there is no unit suffix for a width/height value it is interpreted as using pixel units and then the `svgDpi` option is ignored. Maybe others will have the same problem. Of course, the exported SVGs could be post-processed but this wouldn't be ideal.

I was thinking about adding an option like `defaultSizeRelative` to interpret unitless values as relative values. What's your take on it?

**Comment by dlew** [comment]
Your values aren't unitless, though. They're probably pixel values.

Having two competing methods for determining DPI will be really confusing. How do they interact with each other? Do they interact with each other? What's the difference between the two, to a user who doesn't have this specific problem?

It seems kind of weird to me, because you have two options for fixing it:

1. Export relative sizing.
2. Export pixels, but just make the images the right size.

**Comment by eugenkiss** [comment]
The problem stems from the following points:

* Photoshop cannot export SVG in relative sizing (supposedly)
* Designer wishes to create assets in hdpi instead of mdpi

If Photoshop could export SVGs in relative sizing the problem would be solved. The designer can export in mdpi size but he says hpdi would be preferrable. I reckon the two points above can happen in practice for other users as well.

The only thing that `defaultSizeRelative = true` would do is treat

    <svg ... width="48" height="48" ...>

as

    <svg ... width="48pt" height="48pt" ...>

instead of

    <svg ... width="48px" height="48px" ...>

Just wanted to make the idea clearer ;). If you find this problem too fringe I understand.

**Comment by dlew** [comment]
> Designer wishes to create assets in hdpi instead of mdpi

This sounds like the key problem here.
