### ISSUE TITLE
rasterizeSvgsForDebug does nothing

### ISSUE THREAD

**Issue by robert-wallis** [trello/victor#32]
I'm having trouble configuring victor, I got the plugin installed and in gradle, but when I run `./gradlew rasterizeSvgsForDebug` no new drawables appear in any of my drawable folders and I get this message:

```
9:49:28 PM: Executing external task 'rasterizeSvgsForDebug'...
Configuration on demand is an incubating feature.
:app:rasterizeSvgsForDebug UP-TO-DATE

BUILD SUCCESSFUL

Total time: 2.415 secs
9:49:31 PM: External task execution finished 'rasterizeSvgsForDebug'.
```

My app/build.gradle is something like this:
```
apply plugin: 'com.android.application'
apply plugin: 'com.trello.victor'

android {
    defaultConfig {
    }
    sourceSets {
        main {
            svg.srcDir 'src/main/svg'
        }
    }
    buildTypes {
    }
}
```

Interestingly AndroidStudio (version 1.4, gradle 2.2.1) has a warning on `svg` in the above file
> Cannot resolve symbol 'svg'

But the app builds and runs just fine.
To be clear I have two svg files in `app/src/main/svg` named `ic_row_add.svg` and `ic_row_remove.svg`.

How can I debug this issue to find out why it's not working?

**Comment by dlew** [comment]
victor doesn't add drawables into the drawables folder. It outputs directly to the builds so that your final APK has the PNGs, but your source doesn't (so we don't pollute source control).

**Comment by robert-wallis** [comment]
Thank you, that explains the other issues about AndroidStudio complaining and all that.
