### ISSUE TITLE
Cannot resolve symbol

### ISSUE THREAD

**Issue by IgorGanapolsky** [trello/victor#35]
Hello,
when I use victor, my layout file shows the code for drawable src in red, stating there is a compilation error:
> Cannot resolve symbol @drawable/my_drawable

Isn't there any way to forego these compilation errors, and be able to see the generated PNG in the layout preview?

Igor

**Comment by dlew** [comment]
It's a known issue: https://github.com/trello/victor#known-issues

The app will compile file, it just doesn't think so in Android Studio.

Unfortunately we can't fix it; it has to be the Android tooling team that fixes it.

**Comment by dlew** [comment]
See this issue for the problem: https://code.google.com/p/android/issues/detail?id=160646

**Comment by IgorGanapolsky** [comment]
Thanks for the advise.  And keep up the good work , @dlew @changetip $1.

**Comment by changetip** [comment]
Hi @dlew, @IgorGanapolsky sent you a tip worth 2,361 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/934520)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
