### ISSUE TITLE
Some .svg icons are not shown 

### ISSUE THREAD

**Issue by ungvas** [trello/victor#36]
Hi, thanks for great tool, i have an issue with some svg files, i set them to ImageView but they are not shown...

Is possible that that svgs are broken? By the way in image viewer i can see them ))

Thanks

**Comment by dlew** [comment]
Could you post a sample SVG file that isn't rendering?

Also, by "see them" do you mean you can view the original SVG, or that you can view the PNG rasterization?

**Comment by ungvas** [comment]
Sorry for late answer i forgot...
Here is an svg:
https://www.dropbox.com/s/xakbmaeb5mus69p/taxi%20%282%29.svg?dl=0


 "Also, by "see them" do you mean you can view the original SVG, or that you can view the PNG rasterization?" - I mean that i can see that svg in "Image viewer" or Inkscape ...

Note: How i remember this svg i generated from png with an online tool. Maibe that generator broke the file ))

**Comment by dlew** [comment]
Your problem isn't that the image isn't rendering. It's that it's rendering very small.

Check your `$projectdir/build/generated/res/debug/svg/` directory (or similar). You'll see your PNG there, but just very small.

Try using the `svgDpi` to fix it, or format your SVGs to a more friendly size: https://github.com/trello/victor#usage
