### ISSUE TITLE
Gradle 2.12

### ISSUE THREAD

**Issue by IgorGanapolsky** [trello/victor#37]
I switched to gradle 2.12, and now I am getting an error:
> Failed to apply plugin [id 'com.trello.victor']
   > Could not create an instance of type org.gradle.api.internal.file.DefaultSourceDirectorySet_Decorated.

Please advise,
Igor

**Comment by dlew** [comment]
I'll look into it soon, but for now my advice is to not upgrade to 2.12.

We use `DefaultSourceDirectorySet` but may need to switch to something else...

**Comment by dlew** [comment]
For reference, a thread I started on the Gradle forums about it: https://discuss.gradle.org/t/defaultsourcedirectoryset-alternative/15193/

Apparently we need to implement our own `SourceDirectorySet` since there's no stable one provided by Gradle. Fun times.

**Comment by IgorGanapolsky** [comment]
Indeed, sounds complicated.  Do you think it is still prudent to continue developing Victor, even after android support lib 23.2 supports Vector drawables?

**Comment by dlew** [comment]
There's still no easy way to go straight from SVG -> Android besides Victor. I don't want to run an SVG -> Android drawable wizard every time. So this will remain supported until then. (Maybe someday it'll even do SVG -> Android drawable, if we get time.)

**Comment by IgorGanapolsky** [comment]
On the gradle forum, one guy suggested to do this:
`project.android.sourceSets.all { sourceSet ->
    sourceSet.extensions.add('svg', factory.create('svg'))
}`

Do you think this is a reasonable solution?  I am not familiar enough with Groovy to make a determination...

**Comment by dlew** [comment]
I think that's probably also fine, either solution works. I just went with what the Kotlin plugin chose to do.

**Comment by IgorGanapolsky** [comment]
@dlew  Thanks for the hard work!  Will this be part of 0.1.5 release?  @changetip $1

**Comment by changetip** [comment]
Hi @dlew, I've delivered a tip worth 2,379 bits ($1.00) from @IgorGanapolsky.



**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by dlew** [comment]
0.1.6, though at some point I ought to just call it 1.0. :P

Droidcon SF will probably delay the release (since I'm going to be quite busy for the next couple days), but it'll be out sometime in the next week.
