### ISSUE TITLE
add support to convert SVGs to vector drawables

### ISSUE THREAD

**Issue by stephentalley** [trello/victor#46]
It would be nice if there were an option to instruct Victor to convert svgs to vector drawables instead of pngs.

Using "vectorDrawables.useSupportLibrary = true", the Support Library 23.2 now allows Android to use vector drawables without an intermediate conversion to png.

There are certainly SVG->VectorDrawable converters out there:

- Vector Asset Studio
- [https://github.com/a-student/SvgToVectorDrawableConverter](url)

...but there are no build-time converters, AFAICT.  I suspect Victor has the infrastructure in place to make it the obvious candidate.

This comment from Google suggests a class (VdCommandLineTool.java) that may be of use in this endeavor:

[https://code.google.com/p/android/issues/detail?id=192738#c3](url)

**Comment by dlew** [comment]
This is on the way already: #43 

There's a bit of cleanup to do this week (in particular #45), but I plan on releasing a new version of Victor soon with experimental SVG -> vector drawable support.

**Comment by stephentalley** [comment]
Awesome, thanks!
