### ISSUE TITLE
Question: how can we preview svg in Android Studio like mardown plugin?

### ISSUE THREAD

**Issue by gengjiawen** [trello/victor#61]
This library is fantastic, but for now I have not find a way to preview the svg file in Android studio.So I am wondering is there a way I can achieve this.

**Comment by dlew** [comment]
Unfortunately, the Android tools team has never fixed this bug. There's no way to fix it without their intervention.

**Comment by gengjiawen** [comment]
Anything we can employ like webview in JavaFX ?

**Comment by dlew** [comment]
Closing due to being way out of date.
