### ISSUE TITLE
Question about <> is not supported

### ISSUE THREAD

**Issue by minju0714** [trello/victor#63]
I want to use this svg file (https://ko.wikipedia.org/wiki/%ED%8C%8C%EC%9D%BC:Seoul_subway_linemap_ko.svg)
but when I put this file /main/svg and build project i have some errors
ERROR@ linexx symbol is not supported
ERROR@ linexx use is not supported
...

I think victor can support symbol, use, text, polyline tags.
Is it my fault? How can I resolve this

**Comment by dlew** [comment]
Victor depends on https://xmlgraphics.apache.org/batik/tools/rasterizer.html, so I'd check in with the standalone version of Batik to see if it supports your SVG. If it doesn't, then file an issue there.

**Comment by minju0714** [comment]
svg file that I found it have somthing error :(
thx!!
