### ISSUE TITLE
Deprecated gradle feature

### ISSUE THREAD

**Issue by Dkhusainov** [trello/victor#69]
Gradle: 4.7

Right now while using this pluiging gradle apwms warnings "registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)". Could you please patch it?

**Comment by masc3d** [comment]
now broken with gradle-6.

**Comment by dlew** [comment]
I believe you that it's broken, however I am personally not using Victor anymore and don't have any time to fix it soon (especially given Thanksgiving weekend). PRs are welcome, otherwise I'll try to find some time in December to fix.

**Comment by masc3d** [comment]
would you like a PR for this @dlew

**Comment by dlew** [comment]
I would accept PRs, yes.

**Comment by dlew** [comment]
Fixed by #71
