### ISSUE TITLE
there are many tags not supported

### ISSUE THREAD

**Issue by heavenxue** [trello/victor#76]
In ic_core_1.svg:
ERROR@ line 6 <font> is not supported
ERROR@ line 8 <font-face> is not supported
ERROR@ line 9 <font-face-src> is not supported
ERROR@ line 9 <font-face-name> is not supported
ERROR@ line 10 <missing-glyph> is not supported
ERROR@ line 11 <glyph> is not supported
ERROR@ line 12 <glyph> is not supported
ERROR@ line 13 <glyph> is not supported
ERROR@ line 14 <glyph> is not supported
ERROR@ line 15 <glyph> is not supported
ERROR@ line 16 <glyph> is not supported
ERROR@ line 17 <glyph> is not supported
ERROR@ line 19 <font> is not supported
ERROR@ line 21 <font-face> is not supported
ERROR@ line 22 <font-face-src> is not supported
ERROR@ line 22 <font-face-name> is not supported
ERROR@ line 23 <missing-glyph> is not supported
ERROR@ line 24 <glyph> is not supported
ERROR@ line 25 <glyph> is not supported
ERROR@ line 26 <glyph> is not supported
ERROR@ line 27 <glyph> is not supported
ERROR@ line 28 <glyph> is not supported
ERROR@ line 29 <glyph> is not supported
ERROR@ line 30 <glyph> is not supported
ERROR@ line 31 <glyph> is not supported
ERROR@ line 32 <glyph> is not supported
ERROR@ line 33 <glyph> is not supported
ERROR@ line 34 <glyph> is not supported
ERROR@ line 35 <glyph> is not supported
ERROR@ line 36 <glyph> is not supported
ERROR@ line 37 <glyph> is not supported
ERROR@ line 38 <glyph> is not supported
ERROR@ line 39 <glyph> is not supported
ERROR@ line 40 <glyph> is not supported
ERROR@ line 41 <glyph> is not supported
ERROR@ line 42 <glyph> is not supported
ERROR@ line 43 <glyph> is not supported
ERROR@ line 44 <glyph> is not supported
ERROR@ line 45 <glyph> is not supported
ERROR@ line 46 <glyph> is not supported
ERROR@ line 47 <glyph> is not supported
ERROR@ line 48 <glyph> is not supported
ERROR@ line 49 <glyph> is not supported
ERROR@ line 50 <glyph> is not supported
ERROR@ line 51 <glyph> is not supported
ERROR@ line 52 <glyph> is not supported
ERROR@ line 53 <glyph> is not supported
ERROR@ line 54 <glyph> is not supported
ERROR@ line 55 <glyph> is not supported
ERROR@ line 56 <glyph> is not supported
ERROR@ line 57 <glyph> is not supported
ERROR@ line 58 <glyph> is not supported
ERROR@ line 60 <font> is not supported
ERROR@ line 62 <font-face> is not supported
ERROR@ line 63 <font-face-src> is not supported
ERROR@ line 63 <font-face-name> is not supported
ERROR@ line 64 <missing-glyph> is not supported
ERROR@ line 65 <glyph> is not supported
ERROR@ line 66 <glyph> is not supported
ERROR@ line 67 <glyph> is not supported
ERROR@ line 68 <glyph> is not supported
ERROR@ line 69 <glyph> is not supported
ERROR@ line 70 <glyph> is not supported
ERROR@ line 71 <glyph> is not supported
ERROR@ line 72 <glyph> is not supported
ERROR@ line 73 <glyph> is not supported
ERROR@ line 74 <glyph> is not supported
ERROR@ line 75 <glyph> is not supported
ERROR@ line 76 <glyph> is not supported
ERROR@ line 77 <glyph> is not supported
ERROR@ line 78 <glyph> is not supported
ERROR@ line 79 <glyph> is not supported
ERROR@ line 80 <glyph> is not supported
ERROR@ line 81 <glyph> is not supported
ERROR@ line 82 <glyph> is not supported
ERROR@ line 84 <font> is not supported
ERROR@ line 86 <font-face> is not supported
ERROR@ line 87 <font-face-src> is not supported
ERROR@ line 87 <font-face-name> is not supported
ERROR@ line 88 <missing-glyph> is not supported
ERROR@ line 89 <glyph> is not supported
ERROR@ line 90 <glyph> is not supported
ERROR@ line 91 <glyph> is not supported
ERROR@ line 92 <glyph> is not supported
ERROR@ line 93 <glyph> is not supported
ERROR@ line 94 <glyph> is not supported
ERROR@ line 95 <glyph> is not supported
ERROR@ line 96 <glyph> is not supported
ERROR@ line 97 <glyph> is not supported
ERROR@ line 98 <glyph> is not supported
ERROR@ line 99 <glyph> is not supported
ERROR@ line 100 <glyph> is not supported
ERROR@ line 101 <glyph> is not supported
ERROR@ line 102 <glyph> is not supported
ERROR@ line 103 <glyph> is not supported
ERROR@ line 104 <glyph> is not supported
ERROR@ line 105 <glyph> is not supported
ERROR@ line 106 <glyph> is not supported
ERROR@ line 107 <glyph> is not supported
ERROR@ line 108 <glyph> is not supported
ERROR@ line 109 <glyph> is not supported
ERROR@ line 110 <glyph> is not supported
ERROR@ line 111 <glyph> is not supported
ERROR@ line 113 <font> is not supported
ERROR@ line 115 <font-face> is not supported
ERROR@ line 116 <font-face-src> is not supported
ERROR@ line 116 <font-face-name> is not supported
ERROR@ line 117 <missing-glyph> is not supported
ERROR@ line 118 <glyph> is not supported
ERROR@ line 119 <glyph> is not supported
ERROR@ line 120 <glyph> is not supported
ERROR@ line 121 <glyph> is not supported
ERROR@ line 122 <glyph> is not supported
ERROR@ line 123 <glyph> is not supported
ERROR@ line 124 <glyph> is not supported
ERROR@ line 125 <glyph> is not supported
ERROR@ line 126 <glyph> is not supported
ERROR@ line 127 <glyph> is not supported
ERROR@ line 128 <glyph> is not supported
ERROR@ line 129 <glyph> is not supported
ERROR@ line 130 <glyph> is not supported
ERROR@ line 131 <glyph> is not supported
ERROR@ line 132 <glyph> is not supported
ERROR@ line 133 <glyph> is not supported
ERROR@ line 134 <glyph> is not supported
ERROR@ line 135 <glyph> is not supported
ERROR@ line 136 <glyph> is not supported
ERROR@ line 137 <glyph> is not supported
ERROR@ line 138 <glyph> is not supported
ERROR@ line 139 <glyph> is not supported
ERROR@ line 141 <font> is not supported
ERROR@ line 143 <font-face> is not supported
ERROR@ line 144 <font-face-src> is not supported
ERROR@ line 144 <font-face-name> is not supported
ERROR@ line 145 <missing-glyph> is not supported
ERROR@ line 146 <glyph> is not supported
ERROR@ line 147 <glyph> is not supported
ERROR@ line 153 <text> is not supported

**Comment by dlew** [comment]
There is not enough information here to act on this bug report, so I'm closing it.

We can reopen it if you provide any of the following:

- The source file you're trying to render.
- What you're trying to output (PNG or Android drawable).

Chances are, you are hitting the (known) limits of Victor, though.
