### ISSUE TITLE
Victor does not work with Gradle 7: Type 'com.trello.victor.RasterizeTask' property 'includeDensities' is missing an input or output annotation

### ISSUE THREAD

**Issue by arberg** [trello/victor#80]
When using Gradle 7, in both the source-code sample project and my source code using victor:1.1.0 I get the following error: 

`Type 'com.trello.victor.RasterizeTask' property 'includeDensities' is missing an input or output annotation.`

I've tested it on a fork here: 

https://github.com/arberg/victor/tree/gradle7

**Comment by dlew** [comment]
Very strange; despite having `@Input` on `includeDensities`, it looks like the 1.1.1 build didn't include it somehow.

I'll update to Gradle 7 and also see if a new build puts out the right annotations.

**Comment by dlew** [comment]
Alright, after a lot of wrangling, I've got Victor building with Gradle 7 (both the library and the sample). Let me know if v1.1.2 works for you or not.

**Comment by arberg** [comment]
Cool it works, that was really helpful. Do you have anywhere where I can support your work (paypal etc?)? Possibly pm me at alex@bnr.dk

**Comment by dlew** [comment]
I appreciate the gesture but it's not necessary, I'm just glad that it's working again.
